# -*- coding: utf-8 -*-
"""version4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G4vv1lN5E9DzJJEcRfrTjDb7GGTd3i9F
"""

""" import the required libraries"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def csvFile(n):
  """ reading the csv file and returning the country and year dataframes"""
  d = pd.read_csv(n)
  c = d['Country Name'].tolist()
  c = pd.DataFrame(c, columns = ['Country Name'])
  y = d.iloc[:,1:]
  return c,y

def max_min(c,y):
  """finding out the maximum and minimum areable land for each country"""
  c = c['Country Name'].tolist()
  maximum_arable_land = list(y.max(axis = 1))
  minimum_arable_land = list(y.min(axis = 1))
  ls = [c, maximum_arable_land, minimum_arable_land]
  d = pd.DataFrame(ls).transpose()
  d.columns = ['Country Name','Maximun Arable Land','Minimum Arable Land']
  display(d)

def correaltionMap(path):
  """ Mapping the correlation on different indicators for China """
  data = pd.read_csv(path)
  cormat = sns.heatmap(data.corr(), annot=True,cmap='RdYlGn',linewidths=0.30)
  plt.title("Correlation between different indicators of China\n\n")
  display(cormat)

def bar_plot(c,y):
  """ bar plot for every country """
  cname = c['Country Name'].tolist()
  yname = [i for i in y]
  l = y.values.tolist()
  print("\n")
  plt.figure(figsize=[15,18])
  for i in range(9):
    plt.subplot(3,3,i+1)
    plt.bar(yname,l[i])
    plt.xlabel('Years')
    plt.ylabel('% of Arable Land')
    plt.title(cname[i], size = 15)
  plt.show()
  plt.close()

c,y = csvFile('/content/Arable_land.csv')
display(c,y)
max_min(c,y)

correaltionMap('/content/china.csv')
bar_plot(c,y)

